version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ghcr.io/wy-bbw/qtxml_json_build
        auth:
          username: wy-bbw
          password: $GITHUB_REGISTRY_PASSWORD
    steps:
      - when:
          condition:
            or:
              - equal: [ develop, << pipeline.git.branch >> ]
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - checkout
            - run:
                name: build
                command: |
                  mkdir build
                  cd build
                  conan install .. -s compiler=gcc -s compiler.version=12
                  cmake .. -G Ninja
                  cmake --build .
